services:
  gymtec_api:
    image: ${DOCKER_REGISTRY-}gymtecapi
    build:
      context: .
      dockerfile: GymTec_api/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
  postgresdb:
    image: postgres:latest
    container_name: gymtec_db
    restart: always
    environment:
      POSTGRES_DB: gymtec_db
      POSTGRES_USER: gymtec
      POSTGRES_PASSWORD: gymtec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
      postgres_data: